#!/usr/bin/env bash
# Configure nginx
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22/tcp
sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
