#!/usr/bin/env bash
# Redirect

sudo apt-get -y update
sudo apt-get install -y nginx
sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
