#!/usr/bin/env bash
# Redirect

sudo apt-get -y update
sudo apt-get install -y nginx
sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo sed -i "37i \\\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-enabled/default
sudo service nginx restart
