#!/usr/bin/env bash
# Configure nginx
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22/tcp
sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/ a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
