#!/usr/bin/env bash
# Configure nginx server 2
sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22/tcp
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "30i \\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" /etc/nginx/sites-enabled/default
sudo echo -e "Ceci n'est pas une page\n" > /var/www/html/404.html
sudo sed -i "34i \\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n\t}" /etc/nginx/sites-enabled/default
sed -i '38i \tadd_header X-Served-By $HOSTNAME;\n' /etc/nginx/nginx.conf
sudo service nginx restart
