#!/usr/bin/env bash
#Configure load balancer
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install haproxy=1.8.\*

echo -e "\nbackend web_backend
    balance roundrobin
    server 1593-web-01 34.75.140.59:80 check
    server 1593-web-02 34.75.62.232:80 check" >> /etc/haproxy/haproxy.cfg

echo -e "\nfrontend http
    bind *:80
    mode http
    default_backend web_backend" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
