#!/usr/bin/env bash
# Configure load balancer

sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get update
sudo apt-get install haproxy=1.8.\* -y
echo -e "\nfrontend web_frontend\n\tbind *:80\n\tdefault_backend web_backend" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend web_backend\n\tbalance roundrobin\n\tserver 1593-web-01 34.75.140.59:80 check\n\tserver 1593-web-02 34.75.62.232:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
