#!/usr/bin/env bash
#Display its own pid but its invensible

echo $$ >> /var/run/holbertonscript.pid

trap 'echo "I hate the kill command"' 15
trap 'echo "Y U no love me?!"' 2
trap 'rm /var/run/holbertonscript.pid' 3 15 

while true
do
	echo "To infinity and beyond"
	sleep 2
done
