#!/usr/bin/env bash
#script that kills 4-to_infinity_and_beyond process.
#script that displays:
#
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal
trap echo "I am invincible!!! " 15
while true
do
    echo "To infinity and beyond"
    sleep  2
done
