#!/usr/bin/env bash
#Print 10 times "Holberton school"
#But on the 9th iteration print "hi"
i=1
while [ "$i" -lt 11 ]
do
    echo $i
    case $i in
            4)
                echo "bad luck from China";;
            9)
                echo "bad luck from Japan";;
            17)
                echo "bad luck from Italy";;
    esac
    ((i++))
done
