#!/usr/bin/env bash
#Print 10 times "Holberton school"
#But on the 9th iteration print "hi"
i=0
while [ "$i" -lt 10 ]
do
    if [ $i -eq 8 ]
    then
        echo "Hi"
        ((i++))
    else
        echo "Holberton School"
        ((i++))
    fi
done
