#!/usr/bin/env bash
i=0
while [ "$i" -lt 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
        ((i++))
    fi

    if [ $i -ne 9 ]
    then
        echo "Holberton School"
        ((i++))
    fi
done
