#!/usr/bin/env bash
#display hours from 0 to 12
#display minutes from 1 to 59
i=0
j=1
while [ "$i" -lt 13 ]
do
    j=1
    echo "Hour: $i"
    while [ "$j" -lt 60 ]
    do
        echo "$j"
        ((j++))
    done
    ((i++))
done
